modules/admin/controllers/ApartmentsController.php
<?php


namespace app\modules\admin\controllers;


use app\models\Apartments;
use app\models\ApartmentsType;
use app\models\HousesApartments;
use Yii;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\Controller;
use yii\web\NotFoundHttpException;

class ApartmentsController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                        'matchCallback' => function ($rule, $action) {
                            return Yii::$app->user->identity->is_admin === 1;
                        }
                    ],
                ],
            ],
        ];
    }
    /**
     * Deletes an existing Apartments model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     * @throws \Throwable
     * @throws \yii\db\StaleObjectException
     */
    public function actionDelete($id)
    {
        $houseId = HousesApartments::getHouseId($id);
        $this->findModel($id)->delete();

        return $this->redirect(['houses/view', 'id' => $houseId]);
    }

    /**
     * Updates an existing Apartments model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['houses/view', 'id' => HousesApartments::getHouseId($id)]);
        }

        return $this->render('update', [
            'apartment' => $model,
            'typeList' => ApartmentsType::getTypesArr()
        ]);
    }

    public function actionCreate($houseId)
    {
        $newApartment = new Apartments();
        if($newApartment->load(Yii::$app->request->post()) && $newApartment->validate())
        {
            $newApartment->save();
            HousesApartments::AddApartmentToHouse($houseId, $newApartment->id);
        }
        return $this->redirect(['houses/view', 'id' => $houseId]);
    }

    public function actionCreateTypical($rcId)
    {
        $newApartment = new Apartments();
        if($newApartment->load(Yii::$app->request->post()) && $newApartment->validate())
        {
            $newApartment->save();
            HousesApartments::AddApartmentToResidence($rcId, $newApartment->id);
        }
        return $this->redirect(['default/view', 'id' =>  $rcId]);
    }

    /**
     * Finds the Apartments model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Apartments the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Apartments::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }


}

modules/admin/controllers/HousesController.php
<?php

namespace app\modules\admin\controllers;

use app\models\Apartments;
use app\models\ApartmentsType;
use app\models\HousesApartments;
use app\models\ResidentialComplexes;
use Yii;
use app\models\Houses;
use app\models\HousesSaerch;
use yii\data\Pagination;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * HousesController implements the CRUD actions for Houses model.
 */
class HousesController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                        'matchCallback' => function ($rule, $action) {
                            return Yii::$app->user->identity->is_admin === 1;
                        }
                    ],
                ],
            ],
        ];
    }

    /**
     * Displays a single Houses model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        $model = $this->findModel($id);
        $apartments = Apartments::getApartmentsInHouse($id);
        $pages = new Pagination(['totalCount' => count($apartments)]);
        $pages->setPageSize(12);
        $apartments = array_slice($apartments, $pages->offset, $pages->limit);

        return $this->render('view', [
            'model' => $model,
            'residence' => ResidentialComplexes::findOne($model->residential_com_id),
            'typeList' => ApartmentsType::getTypesArr(),
            'apartmentsList' => $apartments,
            "pages" => $pages
        ]);
    }

    public function actionCreate($rcId)
    {
        $newHouse = new Houses();
        $newHouse->residential_com_id = $rcId;

        if($newHouse->load( Yii::$app->request->post()) && $newHouse->validate())
        {
            $newHouse->save();
        }
        return $this->redirect(['default/view', 'id' =>  $rcId]);
    }
    /**
     * Updates an existing Houses model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Houses model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     * @throws \Throwable
     * @throws \yii\db\StaleObjectException
     */
    public function actionDelete($id)
    {
        $house = $this->findModel($id);
        $rcId = $house->residential_com_id;
        $house->delete();
        return $this->redirect(['default/view', 'id' =>  $rcId]);
    }

    /**
     * Finds the Houses model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Houses the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Houses::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

modules/admin/views/houses/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Houses */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="houses-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

    <div class="form-group">
        <?= Html::submitButton('Сохранить', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

modules/admin/views/houses/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Houses */

$this->title = 'Изменить дом ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Новостройки', 'url' => ['admin']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Изменить дом';
?>
<div class="houses-update">
    <header><?= Html::encode($this->title) ?></header>

    <div class="row">
        <div class="col col-sm-6">
            <?= $this->render('_form', [
                'model' => $model,
            ]) ?>
        </div>
    </div>

</div>

modules/admin/views/houses/view.php
<?php

use app\models\Apartments;
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\widgets\LinkPager;

/* @var $this yii\web\View */
/* @var $model app\models\Houses */
/* @var $typeList array*/
/* @var $apartmentsList array*/
/* @var $residence app\models\ResidentialComplexes */
/* @var $pages */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Новостройки', 'url' => ['/admin']];
$this->params['breadcrumbs'][] = ['label' => $residence->name, 'url' => ['/admin/default/view', 'id' => $residence->id]];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);

?>
<div class="houses-view">
    <header><?= Html::encode($this->title) ?></header>

    <div class="text"><?= Html::encode($residence->city) ?></div>
    <p>
        <?= Html::a('Изменить дом', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Удалить дом', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Вы уверены что хотите удалить дом?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <div class="row">
        <div class="col col-sm-8 apartments-container">
            <?php if (count($apartmentsList)): ?>

                <?php foreach($apartmentsList as $apartment): ?>
                    <div class="card apartment-block">
                        <div class="card-body">
                            <h5 class="card-title">Количество комнат: <?= Html::encode($typeList[$apartment["type_id"]]) ?></h5>
                            <h6 class="card-subtitle mb-2 text-muted">Общая площадь: <?= Html::encode($apartment["total_area"]) ?>кв. м.</h6>
                            <p class="card-text">Цена: <?= Html::encode($apartment["total_price"]) ?>грн.</p>

                            <?= Html::a('Изменить', ['apartments/update', 'id' => $apartment["apartment_id"]], [
                                'class' => 'card-link',
                                'data' => ['method' => 'post'],
                            ]) ?>

                            <?= Html::a('Удалить', ['apartments/delete', 'id' => $apartment["apartment_id"]], [
                                'class' => 'card-link',
                                'data' => [
                                    'method' => 'post',
                                    'confirm' => 'Вы уверены что хотите удалить эту квартиру?'
                                ],
                            ]) ?>
                        </div>
                    </div>
                <?php endforeach ?>

            <?php else: ?>
                <div>Нет квартир</div>
            <?php endif?>

            <?= LinkPager::widget([
                'pagination' => $pages,
            ]); ?>
        </div>
        <div class="col col-sm-4">
            <div class="heading">Создать не типовую квартиру</div>

            <?php $form = ActiveForm::begin(['action' =>['apartments/create', 'houseId' => $model->id]]); ?>

                <?= $this->render('../common/_form_apartments.php', [
                    'typeList' => $typeList,
                    'newApartment' => new Apartments(),
                    'form' => $form
                ]) ?>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>