modules/admin/controllers/DefaultController.php
<?php

namespace app\modules\admin\controllers;

use app\models\ApartmentsType;
use app\models\Houses;
use Yii;
use app\models\ResidentialComplexes;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * DefaultController implements the CRUD actions for ResidentialComplexes model.
 */
class DefaultController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                        'matchCallback' => function ($rule, $action) {
                            return Yii::$app->user->identity->is_admin === 1;
                        }
                    ],
                ],
            ],
        ];
    }

    /**
     * Lists all ResidentialComplexes models.
     * @return mixed
     */
    public function actionIndex()
    {
        $residentialComplexes = ResidentialComplexes::getAllResidentialComplexes();

        return $this->render('index', [
            'residentialComplexes' => $residentialComplexes,
        ]);
    }

    /**
     * Displays a single ResidentialComplexes model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
            'houses' => Houses::getHousesByResidenceId($id),
            'typeList' => ApartmentsType::getTypesArr()
        ]);
    }

    /**
     * Creates a new ResidentialComplexes model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new ResidentialComplexes();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing ResidentialComplexes model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing ResidentialComplexes model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     * @throws \Throwable
     * @throws \yii\db\StaleObjectException
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the ResidentialComplexes model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return ResidentialComplexes the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = ResidentialComplexes::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

modules/admin/controllers/HousesController.php
<?php

namespace app\modules\admin\controllers;

use app\models\Apartments;
use app\models\ApartmentsType;
use app\models\HousesApartments;
use app\models\ResidentialComplexes;
use Yii;
use app\models\Houses;
use app\models\HousesSaerch;
use yii\data\Pagination;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * HousesController implements the CRUD actions for Houses model.
 */
class HousesController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                        'matchCallback' => function ($rule, $action) {
                            return Yii::$app->user->identity->is_admin === 1;
                        }
                    ],
                ],
            ],
        ];
    }

    /**
     * Displays a single Houses model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        $model = $this->findModel($id);
        $apartments = Apartments::getApartmentsInHouse($id);
        $pages = new Pagination(['totalCount' => count($apartments)]);
        $pages->setPageSize(12);
        $apartments = array_slice($apartments, $pages->offset, $pages->limit);

        return $this->render('view', [
            'model' => $model,
            'residence' => ResidentialComplexes::findOne($model->residential_com_id),
            'typeList' => ApartmentsType::getTypesArr(),
            'apartmentsList' => $apartments,
            "pages" => $pages
        ]);
    }

    public function actionCreate($rcId)
    {
        $newHouse = new Houses();
        $newHouse->residential_com_id = $rcId;

        if($newHouse->load( Yii::$app->request->post()) && $newHouse->validate())
        {
            $newHouse->save();
        }
        return $this->redirect(['default/view', 'id' =>  $rcId]);
    }
    /**
     * Updates an existing Houses model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Houses model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     * @throws \Throwable
     * @throws \yii\db\StaleObjectException
     */
    public function actionDelete($id)
    {
        $house = $this->findModel($id);
        $rcId = $house->residential_com_id;
        $house->delete();
        return $this->redirect(['default/view', 'id' =>  $rcId]);
    }

    /**
     * Finds the Houses model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Houses the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Houses::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

modules/admin/views/default/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\ResidentialComplexes */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="residential-complexes-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'city')->textInput(['maxlength' => true]) ?>

    <div class="form-group">
        <?= Html::submitButton('Сохранить', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

modules/admin/views/default/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\ResidentialComplexes */

$this->title = 'Создать жилой комплекс';
$this->params['breadcrumbs'][] = ['label' => 'Новостройки', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="residential-complexes-create">
    <header><?= Html::encode($this->title) ?></header>

    <div class="row">
        <div class="col col-sm-6">
            <?= $this->render('_form', [
                'model' => $model,
            ]) ?>
        </div>
    </div>
</div>

modules/admin/views/default/index.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $residentialComplexes array */

$this->title = 'Новостройки ';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="residential-complexes-index">
    <header><?= Html::encode($this->title) ?></header>
    <p>
        <?= Html::a('Создать жилой комплекс', ['create'], ['class' => 'btn btn-success']) ?>
    </p>
    <div class="rc-container">
        <?php if (count($residentialComplexes)): ?>

            <?php foreach($residentialComplexes as $residentialComplex): ?>
                <div class="card rc-block">
                    <div class="card-body">
                        <?= Html::a(Html::encode($residentialComplex['name']), ['view', 'id' => $residentialComplex['id']], ['class' => 'heading']) ?>
                        <div class="card-subtitle mb-2 text-muted"><?=Html::encode($residentialComplex['city'])?></div>
                    </div>
                </div>
            <?php endforeach; ?>

        <?php else: ?>
            <div>Нет новостроек</div>
        <?php endif ?>
    </div>

</div>

modules/admin/views/default/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\ResidentialComplexes */

$this->title = 'Изменить жилой комплекс: ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Новостройки', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Изменить';
?>
<div class="residential-complexes-update">
    <header><?= Html::encode($this->title) ?></header>

    <div class="row">
        <div class="col col-sm-6">
            <?= $this->render('_form', [
                'model' => $model,
            ]) ?>
        </div>
    </div>
</div>

modules/admin/views/default/view.php
<?php

use app\models\Apartments;
use app\models\Houses;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\ResidentialComplexes */
/* @var $houses array */
/* @var $typeList array */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Новостройки', 'url' => ['/admin']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="residential-complexes-view">
    <header><?= Html::encode($this->title) ?></header>

    <div class="text"><?= Html::encode($model->city) ?></div>
    <p>
        <?= Html::a('Изменить ЖК', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>

        <?= Html::a('Удалить ЖК', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Вы уверены что хотите удалить этот ЖК?',
                'method' => 'post',
            ],
        ]) ?>
    </p>
    <div class="house-container">
        <?php if (count($houses)): ?>
            <?php foreach($houses as $house): ?>
                <div class="card house-block">
                    <div class="card-body">
                        <?= Html::a(Html::encode($house->name), ['houses/view', 'id' => $house->id], ['class' => 'heading']) ?>

                        <?= Html::a('Изменить', ['houses/update', 'id' => $house->id], [
                            'class' => 'card-link',
                            'data' => ['method' => 'post'],
                        ]) ?>

                        <?= Html::a('Удалить', ['houses/delete', 'id' => $house->id], [
                            'class' => 'card-link',
                            'data' => ['method' => 'post', 'confirm' => 'Вы уверены что хотите удалить этот дом?',],
                        ]) ?>
                    </div>
                </div>
            <?php endforeach ?>
        <?php else: ?>
            <div>Нет домов</div>
        <?php endif?>
    </div>
    <div class="row add-container">
        <div class="col col-sm-6">
            <div class="heading">Создать дом</div>

            <?php $form = ActiveForm::begin(['action' =>['houses/create', 'rcId' => $model->id]]); ?>

                <?= $form->field(new Houses(), 'name')->textInput(['maxlength' => true]) ?>

                <?= Html::submitButton('Создать дом', ['class' => 'btn btn-success']) ?>

            <?php ActiveForm::end(); ?>
        </div>
        <div class="col col-sm-6">
            <div class="heading">Создать типовую квартиру</div>

            <?php $form = ActiveForm::begin(['action' =>['apartments/create-typical', 'rcId' => $model->id]]); ?>
                <?= $this->render('../common/_form_apartments.php', [
                    'typeList' => $typeList,
                    'newApartment' => new Apartments(),
                    'form' => $form
                ]) ?>
            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>